modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Library%3A%20Find%20A%20Block%20%28FAB%29"

[[mods]]
modId="fablibrary"
version="1.1"
displayName="FAB Library"
displayURL="https://minecraft.curseforge.com/projects/fab-library"
authors="Rick South"
description="The Find A Block Library assists in finding a specific block and keeping track of its location in a world efficiently."

[[dependencies.fablibrary]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fablibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"